export * from './home/home.component';
export * from './welcome/welcome.component';
export * from './blog/blog.component';
export * from './contact-us/contact-us.component';
export * from './counter/counter.component';
export * from './features/features.component';
export * from './pricing/pricing.component';
export * from './testimonials/testimonials.component';
export * from './work-process/work-process.component';
